version: "3.8"

services:
  pipeops:
    build:
      context: .                   # build context = repo root
      dockerfile: Docker/Dockerfile
    image: apoorvkhanna2/pipeops:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
